# 日志
[log]
# 日志路径, 空将输出控制台
log_path = ""
# log_path = "logs\\server.log"
# log size (M)
max_size = 10
# 压缩日志
compress = true
# 日志保存时间 (day)
max_age = 7
# 日志保存文件数
max_backups = 10
# 日志等级
log_level = "debug"
# 日志类型 text or json
format = "json"

[server]
mode = "debug"
# mode = "release"
sql_path = "sql\\server.sql"
port = 9001

[server.db]
drive_name = "mysql"
dsn = "root:123456@tcp(127.0.0.1:3306)/admin?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
max_idle = 30
max_conn = 60
max_query_time = "180s"
